spring.application.name=journalApp

#spring.mongodb.uri=mongodb://localhost:27017/journaldb
spring.mongodb.uri=mongodb+srv://akshaykumarmathmatics_db_user:VzZESHrzMWezBvpO@cluster0.og0pkvw.mongodb.net/journaldb?appName=Cluster0
# By default indexing cannot created by Spring Boot, we have to tell him to create
spring.data.mongodb.auto-index-creation=true

#spring.security.user.name=akshay
#spring.security.user.password=12345